name: icarus_editor_core
description: Core library package for the Icarus Editor project
version: 0.0.1
homepage: https://github.com/dealloc/icarus_editor

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  build: ^2.3.1
  build_runner: ^2.3.3
  source_gen: ^1.2.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0