name: Generate release
on: 
  push:
    tags:
      - '*'


jobs:
 build_windows:
  strategy:
    matrix:
      os: [{runner: windows-2022, version: 11}, {runner: windows-2019, version: 10}]
  name: Build ${{ matrix.os.version }}
  runs-on: ${{ matrix.os.runner }}
  steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter config --enable-windows-desktop
    - run: flutter build windows --release
      working-directory: ./src/icarus_editor
    - uses: actions/upload-artifact@v3
      with:
        name: icarus_editor_windows${{ matrix.os.version }}
        path: ./src/icarus_editor/build/windows/runner/Release/

 create_release:
    needs: [build_windows]
    strategy:
      matrix:
        os: [{runner: windows-2022, version: 11}, {runner: windows-2019, version: 10}]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.1
        with:
          path: .
      - name: Create Windows ${{ matrix.os.version }} archive
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: '../windows-${{ matrix.os.version }}-x64.zip'
          directory: 'icarus_editor_windows${{ matrix.os.version }}/'

