name: Generate release
on: 
  push:
    tags:
      - '*'

jobs:
 build_windows:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: flutter config --enable-windows-desktop
     - run: flutter build windows --release
       working-directory: ./src/icarus_editor
     - uses: actions/upload-artifact@v3
       with:
         name: icarus_editor_windows
         path: ./src/icarus_editor/build/windows/runner/Release/
 build_linux:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
     - run: flutter config --enable-linux-desktop
     - run: flutter build linux --release
       working-directory: ./src/icarus_editor
     - uses: actions/upload-artifact@v3
       with:
         name: icarus_editor_linux
         path: ./src/icarus_editor/build/linux/x64/release/bundle/
 create_release:
    needs: [build_windows, build_linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.1
        with:
          path: .
      - name: Create Windows archive
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: '../windows-x64.zip'
          directory: 'icarus_editor_windows/'
      - name: Create Linux archive
        uses: thedoctor0/zip-release@main
        with:
          type: 'tar'
          filename: '../linux-x64.tar.gz'
          directory: 'icarus_editor_linux/'
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip,*.tar.gz"
